<a href="https://colab.research.google.com/github/WellingtonMuCe/INTELIGENCIA-ARTIFICIAL-2024-2/blob/main/29_10_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Library

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.4


In [3]:
myArray=np.array([1,2,3,4,5])
print(myArray)

[1 2 3 4 5]


In [4]:
print(type(myArray))


<class 'numpy.ndarray'>


In [7]:
print(myArray.shape)
print(myArray[2])
myArray[2]=29
print(myArray)

(5,)
3
[ 1  2 29  4  5]


In [8]:
myArray1=np.array([[1,2,3],[4,5,6]])
print(myArray1)
print(myArray1.shape)
#

[[1 2 3]
 [4 5 6]]
(2, 3)


In [9]:
myArray3=np.zeros((5,5))
print(myArray3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
myArray4=np.full((3,6),10)
print(myArray4)
myArray5=np.eye(5)
print(myArray5)
myArray6=np.ones((5,5))
print(myArray6)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
myArray7=np.random.random((5,5))
print(myArray7)

[[0.86423855 0.9490044  0.35756013 0.47213678 0.67744735]
 [0.56207008 0.32397641 0.748251   0.52677861 0.47162762]
 [0.77400197 0.92098723 0.66809072 0.89746743 0.84274433]
 [0.3380115  0.43578326 0.6689508  0.67127624 0.24447669]
 [0.84738148 0.39414087 0.85268724 0.86549717 0.42916117]]


In [20]:
myArray8=np.random.randint(100,size=(5,5))
print(myArray8)

[[25 78 27 53 72]
 [86 96 83 66  3]
 [65 84 48 84 68]
 [ 9 27 57  7 68]
 [28 95 61  3 48]]


In [21]:
newMatrix=myArray8[:2,:2]
print(newMatrix)

[[25 78]
 [86 96]]


In [24]:
myArray8[2,2]=100
print(myArray8)

[[ 25  78  27  53  72]
 [ 86  96  83  66   3]
 [ 65  84 100  84  68]
 [  9  27  57   7  68]
 [ 28  95  61   3  48]]


In [25]:
print(myArray8[2,:])

[ 65  84 100  84  68]


In [28]:
print(myArray8[:,2].shape)

(5,)


In [29]:
subMatrix=myArray8[1:4,1:4]
print(subMatrix)

[[ 96  83  66]
 [ 84 100  84]
 [ 27  57   7]]
